[tool.poetry]
name = "fhirstarter-prototype"
version = "0.1.0"
description = "Prototyping and experimentation for a Python FHIR API service"
authors = ["Christopher Sande <christopher.sande@canvasmedical.com>"]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.77.1"
"fhir.resources" = "^6.4.0"
funcy = "^1.17"
more-itertools = "^8.13.0"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
coverage = "^6.4.1"
isort = "^5.10.1"
mypy = "^0.960"
pytest = "^7.1.2"
requests = "^2.28.0"
types-requests = "^2.27.30"
uvicorn = "^0.17.6"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
