[tool.poetry]
name = "fhirstarter-prototype"
version = "0.1.0"
description = "Prototyping and experimentation for a Python FHIR API service"
authors = ["Christopher Sande <christopher.sande@canvasmedical.com>"]

[tool.poetry.dependencies]
python = "^3.10"
black = "^22.3.0"
fastapi = "^0.77.1"
"fhir.resources" = "^6.4.0"
fhirclient = "^3.2.0"
isort = "^5.10.1"
multimethod = "^1.8"
uvicorn = "^0.17.6"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
