[tool.poetry]
name = "fhirstarter"
version = "0.13.1"
description = "An ASGI FHIR API framework built on top of FastAPI and FHIR Resources"
authors = ["Christopher Sande <christopher.sande@canvasmedical.com>"]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.89.1"
"fhir.resources" = "^6.5.0"
lxml = "^4.9.2"
python-multipart = "^0.0.5"
uvloop = "^0.17.0"

[tool.poetry.group.dev.dependencies]
black = "^22.12.0"
funcy = "^1.17"
httpx = "^0.23.3"
isort = "^5.11.4"
mypy = "^0.991"
pytest = "^7.2.1"
requests = "^2.28.2"
types-requests = "^2.28.11.7"
uvicorn = {version = "^0.20.0", extras = ["standard"]}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
check_untyped_defs = true
color_output = true
disallow_incomplete_defs = true
disallow_untyped_calls = true
disallow_untyped_decorators = false
disallow_untyped_defs = true
error_summary = true
follow_imports = "skip"
ignore_missing_imports = true
no_implicit_optional = true
pretty = true
show_error_context = true
strict_equality = true
strict_optional = true
warn_no_return = true
warn_redundant_casts = true
warn_return_any = false
warn_unreachable = true
warn_unused_ignores = true
follow_imports_for_stubs = true
