[tool.poetry]
name = "fhirstarter-prototype"
version = "0.1.0"
description = "Prototyping and experimentation for a Python FHIR API service"
authors = ["Christopher Sande <christopher.sande@canvasmedical.com>"]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.77.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
