name: tests
on:
  push:
    branches:
      - 'main'
  pull_request:
jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fhir-sequence: [STU3, R4B, R5]
    steps:
    - uses: actions/checkout@v3
    - name: Install Poetry
      run: pipx install poetry
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'poetry'
    - name: Install Python packages
      run: |
        poetry add "fhir.resources"@^7.0.2
        poetry install
    - name: Run tests
      env:
        FHIR_SEQUENCE: ${{ matrix.fhir-sequence }}
      run: poetry run pytest
  run-tests-r4:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Poetry
      run: pipx install poetry
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'poetry'
    - name: Install Python packages
      run: |
        poetry add "fhir.resources"@6.4.0
        poetry install
    - name: Run tests
      env:
        FHIR_SEQUENCE: R4
      run: poetry run pytest
